#!/bin/bash

#SBATCH --job-name=imgnetdownload
#SBATCH --partition=normal

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=12000
#SBATCH --time=1-00:00:00

## Set root
root = "/home/amm90/scratch/imagenet/"
cd $root

## Get Train
wget -c "http://www.image-net.org/challenges/LSVRC/2012/dd31405981ef5f776aa17412e1f0c112/ILSVRC2012_img_train.tar" 
## Get Test
wget -c "http://www.image-net.org/challenges/LSVRC/2012/dd31405981ef5f776aa17412e1f0c112/ILSVRC2012_img_test_v10102019.tar"
## Get Val
wget -c "http://www.image-net.org/challenges/LSVRC/2012/dd31405981ef5f776aa17412e1f0c112/ILSVRC2012_img_val.tar"